---
- name: Failed test when helm is not installed
  helm:
    binary_path: "{{ helm_binary}}_fake"
    name: test
    chart_ref: "{{ chart_test }}"
    namespace: "{{ helm_namespace }}"
  ignore_errors: yes
  register: helm_missing_binary

- name: Assert that helm is not installed
  assert:
    that:
      - helm_missing_binary is failed
      - "'No such file or directory' in helm_missing_binary.msg"
