---
name: CI
'on':
  pull_request:
  schedule:
    - cron: '0 6 * * *'

jobs:

  sanity:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.6"]
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: ansible_collections/community/kubernetes

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install ansible-base
        run: pip install git+https://github.com/ansible-collection-migration/ansible-base.git --disable-pip-version-check

      - name: Run sanity tests on Python ${{ matrix.python_version }}
        run: ansible-test sanity --docker -v --color --python ${{ matrix.python_version }}

  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.6"]
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: ansible_collections/community/kubernetes

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install ansible-base
        run: pip install git+https://github.com/ansible-collection-migration/ansible-base.git --disable-pip-version-check

      - name: Run integration tests on Python ${{ matrix.python_version }}
        run: ansible-test integration --docker -v --color --retry-on-error --python ${{ matrix.python_version }} --continue-on-error --diff --coverage

      - name: Upload coverage data
        run: tests/coverage.sh

  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          python_version: ['3.7']
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: ansible_collections/community/kubernetes

      - name: Set up KinD cluster
        uses: engineerd/setup-kind@v0.3.0

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install molecule and openshift dependencies
        run: pip install molecule openshift

      - name: Install ansible-base
        run: pip install git+https://github.com/ansible-collection-migration/ansible-base.git --disable-pip-version-check

      - name: Create default collection path symlink
        run: |
          mkdir -p /home/runner/.ansible
          ln -s /home/runner/work/kubernetes /home/runner/.ansible/collections

      - name: Copy kubernetes integration test role into roles directory.
        run: cp -R tests/integration/targets/kubernetes roles/

      - name: Run molecule default test scenario
        run: molecule --debug test
